Repository prgrms-web-devcourse-final-project/WEB3_4_NDGL_BE, pull requests merged in 2025-04, with the labels that each got.

#28 feat: 댓글 기능 구현
  .gitignore
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentController.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentReqDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/repository/PostCommentRepository.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/security/SecurityConfig.java
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
Labels: feat

#43 feat : like 도메인 병합 및 Swagger, 기초 데이터 로직 추가
  build.gradle
  src/main/java/com/ndgl/spotfinder/domain/like/controller/LikeController.java
  src/main/java/com/ndgl/spotfinder/domain/like/dto/LikeStatus.java
  src/main/java/com/ndgl/spotfinder/domain/like/entity/Like.java
  src/main/java/com/ndgl/spotfinder/domain/like/repository/LikeRepository.java
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/global/app/AppConfig.java
  src/main/java/com/ndgl/spotfinder/global/dev/DevAuthController.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ndgl/spotfinder/global/init/BaseInitData.java
  src/main/java/com/ndgl/spotfinder/global/security/SecurityConfig.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/JwtFilter.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/TokenProvider.java
  src/main/java/com/ndgl/spotfinder/global/springdoc/SpringDocConfig.java
  src/main/resources/application-dev.yml
  src/test/java/com/ndgl/spotfinder/SpotfinderApplicationTests.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
Labels: feat

#59 fix : 좋아요 수/현재 사용자 좋아요 상태 분리
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/like/dto/LikeStatus.java
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
Labels: fix

#61 신고 작성 / 조회, 유저 제재 처리 / 제재 해제 기능 구현
  src/main/java/com/ndgl/spotfinder/SpotfinderApplication.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/report/controller/ReportController.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/BanDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportResponse.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportResponse.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/ReportCreateRequest.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/Ban.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/BanDuration.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/PostCommentReport.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/PostReport.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/ReportStatus.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/ReportType.java
  src/main/java/com/ndgl/spotfinder/domain/report/repository/BanRepository.java
  src/main/java/com/ndgl/spotfinder/domain/report/repository/PostCommentReportRepository.java
  src/main/java/com/ndgl/spotfinder/domain/report/repository/PostReportRepository.java
  src/main/java/com/ndgl/spotfinder/domain/report/scheduler/UserUnbanScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/report/service/ReportService.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/User.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ndgl/spotfinder/global/init/ReportTestInit.java
  src/main/java/com/ndgl/spotfinder/global/security/SecurityConfig.java
  src/test/java/com/ndgl/spotfinder/domain/report/controller/ReportControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/service/ReportServiceTest.java
Labels: feat, fix, refactor

#68 포스트 조회 시 좋아요 개수 및 댓글 개수 포함 및 조회 쿼리 수 최적화
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostDetailResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: fix

#84 Jpa like 검색 구현 / elastic search 검색 연동
  build.gradle
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentReqDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/repository/PostCommentRepository.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/search/controller/PostSearchController.java
  src/main/java/com/ndgl/spotfinder/domain/search/document/PostDocument.java
  src/main/java/com/ndgl/spotfinder/domain/search/repository/PostSearchRepository.java
  src/main/java/com/ndgl/spotfinder/domain/search/service/PostSearchService.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticSearchConfig.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticSearchHealthCheck.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticSearchInitIndexer.java
  src/main/java/com/ndgl/spotfinder/global/init/BaseInitData.java
  src/main/resources/application.yml
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
Labels: feat, fix

#90 팔로우 API, 블로그 목록 API, 팔로우한 블로그 조회 API 구현, 포스트 및 댓글 조회 시 작성자 ID 추가 등
  src/main/java/com/ndgl/spotfinder/domain/blog/controller/BlogApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/blog/controller/BlogController.java
  src/main/java/com/ndgl/spotfinder/domain/blog/dto/BlogResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/blog/dto/PostSummeryDto.java
  src/main/java/com/ndgl/spotfinder/domain/blog/service/BlogService.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentDto.java
  src/main/java/com/ndgl/spotfinder/domain/follow/controller/FollowApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/follow/controller/FollowController.java
  src/main/java/com/ndgl/spotfinder/domain/follow/entity/Follow.java
  src/main/java/com/ndgl/spotfinder/domain/follow/repository/FollowRepository.java
  src/main/java/com/ndgl/spotfinder/domain/follow/service/FollowService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/HashtagDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/LocationDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostDetailResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/search/document/PostDocument.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/User.java
  src/main/java/com/ndgl/spotfinder/domain/user/repository/UserRepository.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/common/dto/SliceRequest.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
Labels: feat, fix

#98 feat : S3 이미지 CRD, 포스트 임시 저장 생성 및 불러오기, 자동 정리 등
  .github/workflows/test.yml
  build.gradle
  src/main/java/com/ndgl/spotfinder/domain/image/controller/ImageApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/image/controller/ImageController.java
  src/main/java/com/ndgl/spotfinder/domain/image/dto/ImageUrlRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/image/dto/PresignedUrlsResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/image/dto/UploadCompleteRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/image/entity/Image.java
  src/main/java/com/ndgl/spotfinder/domain/image/repository/ImageRepository.java
  src/main/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupService.java
  src/main/java/com/ndgl/spotfinder/domain/image/service/ImageService.java
  src/main/java/com/ndgl/spotfinder/domain/image/type/ImageUsage.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCommonUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostTempResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostTempUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/PostStatus.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/async/AsyncConfig.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Config.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Service.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Util.java
  src/main/java/com/ndgl/spotfinder/global/exception/CustomS3Exception.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/initData/BaseInitData.java
  src/main/java/com/ndgl/spotfinder/global/initData/ReportTestInit.java
  src/main/java/com/ndgl/spotfinder/global/util/Ut.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: feat

#118 fix: Image Index ImageType to ImageUsage
  src/main/java/com/ndgl/spotfinder/domain/image/entity/Image.java
Labels: bug

#124 Fix/test yml 0409
  .github/workflows/test.yml
  src/main/java/com/ndgl/spotfinder/domain/image/entity/Image.java
Labels: test

#130 팔로우 및 블로그 테스트 코드 작성, 자기 자신 팔로우/언팔로우 예외처리
  src/main/java/com/ndgl/spotfinder/domain/blog/dto/PostSummeryDto.java
  src/main/java/com/ndgl/spotfinder/domain/blog/service/BlogService.java
  src/main/java/com/ndgl/spotfinder/domain/follow/service/FollowService.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/resources/application-test.yml
  src/test/java/com/ndgl/spotfinder/domain/blog/BlogServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/follow/FollowServiceTest.java
Labels: fix, test

#137 좋아요 상태 POST 및 COMMENT 조회, 좋아요 연동 삭제 적용
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentController.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/like/controller/LikeApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/like/controller/LikeController.java
  src/main/java/com/ndgl/spotfinder/domain/like/entity/Like.java
  src/main/java/com/ndgl/spotfinder/domain/like/entity/Likeable.java
  src/main/java/com/ndgl/spotfinder/domain/like/repository/LikeRepository.java
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostDetailResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/dev/DevAuthController.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/initData/BaseInitData.java
  src/main/java/com/ndgl/spotfinder/global/util/Ut.java
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: feat, refactor

#139 마이페이지 조회, 회원 정보 수정 기능, 회원 탈퇴 기능 버그 수정.
  src/main/java/com/ndgl/spotfinder/domain/user/controller/UserController.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserModifiedRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserModifiedResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/User.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
Labels: fix

#144 ELK 를 EC2에 배포하기 위한 elk-deploy.yml 파일 추가
  elk-deploy.yml
Labels: feat

#146 deploy.yml 에 filebeat 까지 활용되도록 docker-compose 적용
  .github/workflows/deploy.yml
Labels: fix

#147 elk-deploy.yml 올바른 패키지로 이동
  .github/workflows/elk-deploy.yml
Labels: fix

#148 deploy.yml 의 elk/prod 디렉토리 생성하지 않아 발생한 에러 해결
  .github/workflows/deploy.yml
Labels: fix

#149 elk-deploy.yml 의 쌍따옴표를 작은따옴표로 변경
  .github/workflows/elk-deploy.yml
Labels: fix

#150 fix: elk-deploy.yml 의 오타 수정
  .github/workflows/elk-deploy.yml
Labels: fix

#151 테스트를 위해 임시로 스케줄링 off
  src/main/java/com/ndgl/spotfinder/domain/popular/scheduler/PopularTrendsScheduler.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticsearchIndexingScheduler.java
Labels: fix

#152 deploy, elk-deploy 파일 오류 수정
  .github/workflows/deploy.yml
  .github/workflows/elk-deploy.yml
Labels: fix

#153 deploy.yml 바꿔서 정상 동작 확인 시도
  .github/workflows/deploy.yml
Labels: fix

#154 deploy.yml 바꿔서 정상 동작 확인 시도2
  .github/workflows/deploy.yml
Labels: fix

#155 fix: deploy.yml 바꿔서 정상 동작 확인 시도3
  .github/workflows/deploy.yml
Labels: fix

#156 deploy.yml, elk-deploy.yml 바꿔서 정상 동작 확인 시도4
  .github/workflows/deploy.yml
  .github/workflows/elk-deploy.yml
Labels: fix

#157 deploy.yml, elk-deploy.yml 바꿔서 시도 6
  .github/workflows/deploy.yml
  .github/workflows/elk-deploy.yml
Labels: fix

#158 prod 에도 로그 생성되도록 logback 수정
  src/main/resources/logback-spring.xml
Labels: fix

#159 deploy.yml FILEBEAT 오타 수정
  .github/workflows/deploy.yml
Labels: fix

#160 관리자 도메인 리팩토링 -> Swagger 관련 Controller 에 대한 ApiSpecification 추가, DTO 명명 규칙 반영
  src/main/java/com/ndgl/spotfinder/domain/admin/controller/AdminApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/admin/controller/AdminController.java
  src/main/java/com/ndgl/spotfinder/domain/admin/dto/AdminCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/admin/dto/AdminCreateResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/admin/dto/CreateAdminResponse.java
  src/main/java/com/ndgl/spotfinder/domain/admin/service/AdminService.java
  src/main/java/com/ndgl/spotfinder/global/common/util/MaskingUtil.java
  src/test/java/com/ndgl/spotfinder/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/admin/service/AdminServiceTest.java
Labels: refactor

#161 Feature/report신고 도메인 리팩토링 -> Swagger 관련 Controller 에 대한 ApiSpecification 추가, DTO 명명 규칙 반영
  src/main/java/com/ndgl/spotfinder/domain/report/controller/ReportApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/report/controller/ReportController.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/BanDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportResponse.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportResponse.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/ReportCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/ReportType.java
  src/main/java/com/ndgl/spotfinder/domain/report/repository/PostCommentReportRepository.java
  src/main/java/com/ndgl/spotfinder/domain/report/repository/PostReportRepository.java
  src/main/java/com/ndgl/spotfinder/domain/report/service/ReportService.java
  src/test/java/com/ndgl/spotfinder/domain/report/controller/ReportControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/service/ReportServiceTest.java
Labels: refactor

#164 elk-deploy 오타 해결
  .github/workflows/elk-deploy.yml
Labels: fix

#163 포스트 조회수 증가 로직 구현, 팔로우 확인 API 구현
  src/main/java/com/ndgl/spotfinder/domain/follow/FollowCheckResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/follow/controller/FollowController.java
  src/main/java/com/ndgl/spotfinder/domain/follow/service/FollowService.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/scheduler/PostViewSyncScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostViewCountService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/aspect/ViewCountAspect.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/redis/RedisConfig.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/TokenProvider.java
  src/main/java/com/ndgl/spotfinder/global/security/refresh/entity/RefreshToken.java
  src/main/java/com/ndgl/spotfinder/global/security/refresh/repository/RefreshTokenRepository.java
  src/main/java/com/ndgl/spotfinder/global/security/refresh/service/RefreshTokenService.java
Labels: feat, fix

#165 User 로그인 restClient 방식으로 개선, 로그인 테스트를 위한 log 명령어 추가, 유저 탈퇴 시 소프트 딜리트 방식 변경
  src/main/java/com/ndgl/spotfinder/domain/user/client/GoogleAuthClientImpl.java
  src/main/java/com/ndgl/spotfinder/domain/user/client/GoogleUserInfoClient.java
  src/main/java/com/ndgl/spotfinder/domain/user/client/RestTemplateGoogleAuthClient.java
  src/main/java/com/ndgl/spotfinder/domain/user/controller/UserController.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/RestClientDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserResignedResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/User.java
  src/main/java/com/ndgl/spotfinder/domain/user/repository/OauthRepository.java
  src/main/java/com/ndgl/spotfinder/domain/user/repository/UserRepository.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/OauthService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/config/RestClientConfig.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
Labels: bug, fix

#174 build.gradle commons-logging 충돌 해결
  build.gradle
  src/main/java/com/ndgl/spotfinder/domain/popular/scheduler/PopularTrendsScheduler.java
Labels: fix

#175 fix: 디버깅을 위해 ControllerLoggingAspect 주석 처리
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#177 ControllerLoggingAspect 의 maskedArgs 주석 처리 시도
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#178 ControllerLoggingAspect 의 RequestLogContext 주석처리
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#179 ControllerLoggingAspect 주석 처리
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#180 ControllerLoggingAspect 에서 HttpServletResponse 를 인자로 받는 메서드 제외
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#181 ControllerLoggingAspect의 completeLogMap 누락 수정
  src/main/java/com/ndgl/spotfinder/global/aspect/logging/ControllerLoggingAspect.java
Labels: fix

#173 댓글 고정 & 검색어 자동완성 기능 추가
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentController.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostCommentStatus.java
  src/main/java/com/ndgl/spotfinder/domain/comment/repository/PostCommentRepository.java
  src/main/java/com/ndgl/spotfinder/domain/comment/scheduler/PostCommentDeleteScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/report/service/ReportService.java
  src/main/java/com/ndgl/spotfinder/domain/search/controller/PostSearchApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/search/controller/PostSearchController.java
  src/main/java/com/ndgl/spotfinder/domain/search/repository/PostSearchRepositoryCustom.java
  src/main/java/com/ndgl/spotfinder/domain/search/repository/PostSearchRepositoryImpl.java
  src/main/java/com/ndgl/spotfinder/domain/search/service/PostSearchService.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/service/ReportServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
Labels: feat

#188 Like 타 도메인 Serivce 주입 → Repository, Ut 폴더 이동
  src/main/java/com/ndgl/spotfinder/domain/comment/controller/PostCommentController.java
  src/main/java/com/ndgl/spotfinder/domain/image/service/ImageService.java
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Service.java
  src/main/java/com/ndgl/spotfinder/global/common/util/CommonUtil.java
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
Labels: chore

#192 인기 게시물 목록 캐싱 효율화, 인기 검색어 / 게시물 사이즈 통일, 변경 로직에 맞게 테스트 수정
  src/main/java/com/ndgl/spotfinder/domain/popular/constants/PopularConstants.java
  src/main/java/com/ndgl/spotfinder/domain/popular/scheduler/PopularTrendsScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/popular/service/elasticsearch/ElasticsearchPopularService.java
  src/main/java/com/ndgl/spotfinder/domain/popular/service/redis/RedisPopularService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/search/controller/PostSearchController.java
  src/main/java/com/ndgl/spotfinder/domain/search/service/PostSearchService.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticsearchIndexingScheduler.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/test/java/com/ndgl/spotfinder/domain/popular/elasticsearch/ElasticsearchPopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/popular/redis/RedisPopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
Labels: feat, fix, test

#196 포스트 및 해시태그 조회 로직 수정, Redis 사용하는 코드 수정, 포스트 목록의 내용 가공해서 표시
  build.gradle
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostViewCountDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/scheduler/PostViewSyncScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostViewCountService.java
  src/main/java/com/ndgl/spotfinder/global/common/util/MarkdownUtil.java
  src/main/java/com/ndgl/spotfinder/global/common/util/StringUtil.java
  src/main/java/com/ndgl/spotfinder/global/redis/RedisConfig.java
Labels: fix

#197 Swagger에 API 사양서 작성 (User 도메인, Auth도메인)
  src/main/java/com/ndgl/spotfinder/domain/auth/controller/AuthApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/auth/controller/AuthController.java
  src/main/java/com/ndgl/spotfinder/domain/user/controller/UserApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/user/controller/UserController.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserJoinRequestDto.java
Labels: docs, feat

#198 Prod 환경 es 검색 활성화
  src/main/resources/application-prod.yml
Labels: chore

#200 이미지 관련 및 ErrorCode 수정
  src/main/java/com/ndgl/spotfinder/domain/image/dto/UploadCompleteRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/image/service/ImageService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCommonUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostTempResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Service.java
  src/main/java/com/ndgl/spotfinder/global/exception/CustomS3Exception.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: chore

#206 POST 검색시 Public Status만 조회, 섬네일 이미지 변경 및 제거 시 리소스 제거 로직 추가
  src/main/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupService.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/async/AsyncConfig.java
  src/main/java/com/ndgl/spotfinder/global/aws/s3/S3Service.java
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupServiceTest.java
Labels: fix

#210 POST 임시에서 공개로 발행시 생성일 변경 및 Order By 변경
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCommonUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/base/BaseTime.java
Labels: fix

#214 공개 상태 포스트만 검색되도록 수정 & fetch join 관련 수정
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/search/document/PostDocument.java
  src/main/java/com/ndgl/spotfinder/domain/search/repository/PostSearchRepositoryImpl.java
  src/main/java/com/ndgl/spotfinder/domain/search/service/PostSearchService.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticsearchIndexingScheduler.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
Labels: fix

#217 비로그인 상태에서 블로그 글 조회 가능하도록 처리, ErrorCode, 패키지 이름 및 SecurityConfig 정리
  src/main/java/com/ndgl/spotfinder/domain/blog/controller/BlogController.java
  src/main/java/com/ndgl/spotfinder/domain/blog/service/BlogService.java
  src/main/java/com/ndgl/spotfinder/domain/comment/dto/PostCommentResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
  src/main/java/com/ndgl/spotfinder/domain/comment/service/PostCommentService.java
  src/main/java/com/ndgl/spotfinder/domain/comment/type/PostCommentStatus.java
  src/main/java/com/ndgl/spotfinder/domain/like/controller/LikeController.java
  src/main/java/com/ndgl/spotfinder/domain/like/entity/Like.java
  src/main/java/com/ndgl/spotfinder/domain/like/repository/LikeRepository.java
  src/main/java/com/ndgl/spotfinder/domain/like/service/LikeService.java
  src/main/java/com/ndgl/spotfinder/domain/like/type/TargetType.java
  src/main/java/com/ndgl/spotfinder/domain/popular/service/redis/RedisPopularService.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCommonUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostTempResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/post/type/PostStatus.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/BanDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostCommentReportResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/PostReportResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/dto/ReportCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/Ban.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/PostCommentReport.java
  src/main/java/com/ndgl/spotfinder/domain/report/entity/PostReport.java
  src/main/java/com/ndgl/spotfinder/domain/report/service/ReportService.java
  src/main/java/com/ndgl/spotfinder/domain/report/type/BanDuration.java
  src/main/java/com/ndgl/spotfinder/domain/report/type/ReportStatus.java
  src/main/java/com/ndgl/spotfinder/domain/report/type/ReportType.java
  src/main/java/com/ndgl/spotfinder/domain/search/document/PostDocument.java
  src/main/java/com/ndgl/spotfinder/domain/search/document/SearchType.java
  src/main/java/com/ndgl/spotfinder/domain/search/repository/PostSearchRepositoryImpl.java
  src/main/java/com/ndgl/spotfinder/domain/search/service/PostSearchService.java
  src/main/java/com/ndgl/spotfinder/domain/search/type/SearchType.java
  src/main/java/com/ndgl/spotfinder/domain/user/client/GoogleAuthClientImpl.java
  src/main/java/com/ndgl/spotfinder/domain/user/dto/UserJoinRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/Oauth.java
  src/main/java/com/ndgl/spotfinder/domain/user/repository/OauthRepository.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/OauthService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/domain/user/type/Provider.java
  src/main/java/com/ndgl/spotfinder/global/config/RestTemplateConfig.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/initdata/BaseInitData.java
  src/main/java/com/ndgl/spotfinder/global/initdata/ReportTestInit.java
  src/main/java/com/ndgl/spotfinder/global/security/SecurityConfig.java
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/popular/redis/RedisPopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/controller/ReportControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/service/ReportServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/user/controller/UserControllerTest.java
Labels: chore, fix, refactor

#222 UserControllerTest.java 테스트 양식 통일, 실패 케이스 추가
  src/test/java/com/ndgl/spotfinder/domain/user/controller/UserControllerTest.java
Labels: test

#223 Comment, Search 테스트명 양식 통일
  src/test/java/com/ndgl/spotfinder/domain/comment/service/PostCommentServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/search/PostSearchServiceTest.java
Labels: test

#218 Report, Admin, Popular 도메인의 테스트 클래스들을 메서드명 규칙에 맞게 통일
  src/test/java/com/ndgl/spotfinder/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/admin/service/AdminServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/popular/PopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/popular/elasticsearch/ElasticsearchPopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/popular/redis/RedisPopularServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/controller/ReportControllerTest.java
  src/test/java/com/ndgl/spotfinder/domain/report/service/ReportServiceTest.java
Labels: test

#221 PostComment 삭제 시 PostCommentReport 로 삭제되도록 설정
  src/main/java/com/ndgl/spotfinder/domain/comment/entity/PostComment.java
Labels: fix

#224 Post 엔티티에 Soft Delete + 스케줄러를 활용한 Hard Delete 배치처리 도입
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/scheduler/PostDeletionScheduler.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/post/type/PostStatus.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: feat, test

#225 test : Like, image, post 테스트 명 통일 및 public 제거
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageCleanupServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/image/service/ImageServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/like/service/LikeServiceTest.java
Labels: test

#226 테스트 코드 네이밍 수정
  src/test/java/com/ndgl/spotfinder/domain/blog/BlogServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/follow/FollowServiceTest.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: test

#228 블로그 목록 조회 시 사용자의 임시 글이 보이는 버그 수정
  src/main/java/com/ndgl/spotfinder/domain/blog/dto/BlogResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/blog/dto/PostSummaryDto.java
  src/main/java/com/ndgl/spotfinder/domain/blog/service/BlogService.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/test/java/com/ndgl/spotfinder/domain/blog/BlogServiceTest.java
Labels: bug

#229 fix : Lock으로 동시 접근 방지
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
Labels: fix

#231 fix: 포스트 생성 시간이 변경되지 않도록 수정
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCommonUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/global/base/BaseTime.java
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: fix

#232 부분 인덱싱 로직 수정
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/global/elk/ElasticsearchIndexingScheduler.java
Labels: bug

#233 이미지 패턴 img 태그 및 s3 자체 url까지 고려
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
Labels: bug

#234 README 수정
  README.md
Labels: docs

#235 JWT 갱신 로직 변경
  infra/main.tf
  infra/network.tf
  infra/variables.tf
  src/main/java/com/ndgl/spotfinder/domain/admin/controller/AdminController.java
  src/main/java/com/ndgl/spotfinder/domain/auth/controller/AuthApiSpecification.java
  src/main/java/com/ndgl/spotfinder/domain/auth/controller/AuthController.java
  src/main/java/com/ndgl/spotfinder/domain/auth/service/AuthService.java
  src/main/java/com/ndgl/spotfinder/domain/user/service/UserService.java
  src/main/java/com/ndgl/spotfinder/global/security/cookie/TokenCookieUtil.java
  src/main/java/com/ndgl/spotfinder/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/JwtFilter.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/TokenProvider.java
Labels: refactor

#236 로그인 안되는 문제 해결.
  src/main/java/com/ndgl/spotfinder/global/security/cookie/TokenCookieUtil.java
Labels: bug
