Repository prgrms-web-devcourse-final-project/WEB3_4_NDGL_BE, pull requests merged in 2025-03, with the labels that each got.

#12 Slice Dto 구현, RsData의 code 자료형 HttpStatus -> Integer 로 수정, build.gradle 에 AOP 설정 추가
  build.gradle
  src/main/java/com/ndgl/spotfinder/global/aspect/ResponseAspect.java
  src/main/java/com/ndgl/spotfinder/global/common/dto/SliceRequest.java
  src/main/java/com/ndgl/spotfinder/global/common/dto/SliceResponse.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ndgl/spotfinder/global/rsdata/RsData.java
Labels: feat, fix

#14 feat : GlobalExceptionHandler @ControllerAdvice to @RestControllerAdvice
  src/main/java/com/ndgl/spotfinder/global/aspect/ResponseAspect.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
Labels: fix

#17 fix: SliceRequest 의 size 자료형 long -> int 로 변경
  src/main/java/com/ndgl/spotfinder/global/common/dto/SliceRequest.java
Labels: fix

#27 포스트 생성, 수정, 삭제 기능 구현, 포스트를 페이지 단위로 조회하는 기능 구현
  .gitignore
  src/main/java/com/ndgl/spotfinder/domain/post/controller/PostController.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/HashtagDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/LocationDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostResponseDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Hashtag.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Location.java
  src/main/java/com/ndgl/spotfinder/domain/post/entity/Post.java
  src/main/java/com/ndgl/spotfinder/domain/post/repository/PostRepository.java
  src/main/java/com/ndgl/spotfinder/domain/post/service/PostService.java
  src/main/java/com/ndgl/spotfinder/domain/user/entity/User.java
  src/main/java/com/ndgl/spotfinder/global/aspect/ResponseAspect.java
  src/main/java/com/ndgl/spotfinder/global/exception/ErrorCode.java
  src/main/java/com/ndgl/spotfinder/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ndgl/spotfinder/global/security/SecurityConfig.java
  src/main/java/com/ndgl/spotfinder/global/security/cookie/TokenCookieUtil.java
  src/main/java/com/ndgl/spotfinder/global/security/jwt/TokenProvider.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/ndgl/spotfinder/domain/post/PostServiceTest.java
Labels: feat, test
